### ISSUE TITLE
Runtime error: RT not found

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#65]
The following error is keeping things from running:

```
ERROR:nipype.workflow:Saving crash info to /data/crash-20190130-014840-root-loader-1afd77df-e8fa-4e08-94d8-903e350e6e78.pklz
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/src/fitlins/fitlins/interfaces/bids.py", line 180, in _run_interface
    analysis.setup(drop_na=False, desc='preproc', **selectors)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 89, in setup
    b.setup(input_nodes, drop_na=drop_na, **selectors)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 190, in setup
    **kwargs)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 576, in get_collections
    skip_empty=skip_empty, **kwargs)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/bids/variables/io.py", line 76, in load_variables
    dataset = _load_time_variables(layout, dataset, **_kwargs)
  File "/opt/conda/envs/neuro/lib/python3.6/site-packages/bids/variables/io.py", line 162, in _load_time_variables
    full_search=True)['RepetitionTime']
KeyError: 'RepetitionTime'


```

**Comment by effigies** [comment]
You need to copy the original `*bold.json` files into your derivatives (cleaning anything irrelevant), since `BIDSLayout` no longer associates metadata from the original dataset with derivatives.

**Comment by adelavega** [comment]
Thx. Actually been doing that for a while, so not sure its not finding it. Will take a look soon
