### ISSUE TITLE
error when running analyses on raiders dataset

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout-cli#91]
This is the traceback of the error thrown when trying to run analyses on one subject *rid000005* (all runs) from the Raiders dataset via neuroscout-cli (on Mac).

Same error both when pulling latest version of Neuroscout-cli via docker, and when pulling version-0.3.

It actually runs for quite some time before throwing the error, so it might be an issue with one specific run?

```
INFO:nipype.workflow:***********************************`

191211-01:31:04,763 nipype.workflow ERROR:
         could not run node: fitlins_wf.l3_model
ERROR:nipype.workflow:could not run node: fitlins_wf.l3_model
191211-01:31:04,764 nipype.workflow INFO:
         crashfile: /work/crash-20191211-012550-root-l3_model-fda10497-88fe-49dd-b40b-3f370e708124.txt
INFO:nipype.workflow:crashfile: /work/crash-20191211-012550-root-l3_model-fda10497-88fe-49dd-b40b-3f370e708124.txt
191211-01:31:04,769 nipype.workflow INFO:
         ***********************************
INFO:nipype.workflow:***********************************
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 11, in <module>
    load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')()
  File "/src/neuroscout/neuroscout_cli/cli.py", line 60, in main
    command(deepcopy(args)).run()
  File "/src/neuroscout/neuroscout_cli/commands/run.py", line 57, in run
    retcode = run_fitlins(fitlins_args)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 214, in run_fitlins
    analysis.setup(**selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 89, in setup
    b.setup(input_nodes, drop_na=drop_na, **selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 190, in setup
    **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 876, in get_collections
    skip_empty=skip_empty, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/variables/io.py", line 81, in load_variables
    dataset = _load_time_variables(layout, dataset, scope=scope, **_kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/variables/io.py", line 262, in _load_time_variables
    _data = pd.read_csv(cf.path, sep='\t', na_values='n/a')
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/work/Raiders/preproc/fmriprep/sub-rid000005/func/sub-rid000005_task-raiders_acq-8ch326vol_run-04_desc-confounds_regressors.tsv' does not exist: b'/work/Raiders/preproc/fmriprep/sub-rid000005/func/sub-rid000005_task-raiders_acq-8ch326vol_run-04_desc-confounds_regressors.tsv'
```

**Comment by adelavega** [comment]
Thanks. I think the issue here is that it should be ignoring that type of file coming from fmriprep, as all the events (including) confounds, should come from the bundle that Neuroscout originates. Will dig into it.

**Comment by adelavega** [comment]
Let me know if it works with 0.3

**Comment by rbroc** [comment]
> Let me know if it works with 0.3
it doesn't, the traceback actually comes from the 0.3 error.
